services:
  - type: web
    name: test-case-manager
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: TEAM_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
